[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = ["django", "environ",]

[tool.djlint]
profile="django"
ignore = "H031,H006,H030"
